"""
Generates a fully self-contained Python script for submission as a SpiNNaker
batch job via nmpi (see notebooks/spinnaker_lif_shd_deploy.ipynb). The job
runner sandbox only sees the single uploaded file, so this embeds:
  - the exported+folded sparch weights (base64-encoded .npz bytes)
  - a handful of real SHD test examples' spike times (same encoding)
  - the pynn_lif_model.py network-building logic, inlined as source
  - a small driver that builds the network with pyNN.spiNNaker, runs it,
    and prints per-example predictions + a summary accuracy line.

Usage:
    python generate_spinnaker_script.py --weights PATH --shd_h5 PATH
        --n_examples N --seed N --out OUT.py
"""
import argparse
import base64
import io
import os

import h5py
import numpy as np

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_SRC_PATH = os.path.join(REPO_ROOT, "src", "pynn_lif_model.py")


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--weights",
        default=os.path.join(REPO_ROOT, "src", "data", "shd_lif_weights.npz"),
    )
    parser.add_argument(
        "--shd_h5",
        default=os.path.join(
            os.path.dirname(REPO_ROOT), "sparch", "shd_dataset", "shd_test.h5"
        ),
    )
    parser.add_argument("--n_examples", type=int, default=10)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--out",
        default=os.path.join(REPO_ROOT, "spinnaker_job_generated.py"),
    )
    return parser.parse_args()


def npz_to_b64(npz_path):
    with open(npz_path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")


def build_examples_npz_b64(shd_h5_path, n_examples, seed):
    f = h5py.File(shd_h5_path, "r")
    times = f["spikes"]["times"]
    units = f["spikes"]["units"]
    labels = np.array(f["labels"])

    rng = np.random.default_rng(seed)
    indices = rng.choice(len(labels), size=n_examples, replace=False)

    out = {}
    for j, i in enumerate(indices):
        out[f"example{j}_times"] = np.array(times[i])
        out[f"example{j}_units"] = np.array(units[i])
        out[f"example{j}_label"] = int(labels[i])
    out["n_examples"] = n_examples

    buf = io.BytesIO()
    np.savez(buf, **out)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def read_model_src():
    with open(MODEL_SRC_PATH) as f:
        src = f.read()
    # Strip the module docstring's leading import line duplication concerns --
    # keep as-is, the generated script re-imports numpy/scipy itself anyway.
    return src


TEMPLATE = '''\
"""
Auto-generated by hdc-language/src/generate_spinnaker_script.py -- DO NOT
EDIT BY HAND. Self-contained SpiNNaker batch job: builds the sparch-trained
LIF/SHD network via pyNN.spiNNaker from embedded weights, runs it on
{n_examples} real SHD test examples, and prints per-example predictions plus
a summary accuracy line (both PyNN's spike-count-argmax prediction and the
true label -- there is no local sparch/torch available in this sandbox to
also compute the softmax-argmax reference; that comparison is done locally
via verification/pynn_smoke_test.py before submitting this job).
"""
import base64
import io

import numpy as np

# --- embedded data (weights + test examples) --------------------------------
_WEIGHTS_NPZ_B64 = "{weights_b64}"
_EXAMPLES_NPZ_B64 = "{examples_b64}"


def _load_b64_npz(b64_str):
    return np.load(io.BytesIO(base64.b64decode(b64_str)))


# --- pynn_lif_model.py, inlined ---------------------------------------------

{model_src}

# --- driver ------------------------------------------------------------------


def main():
    import pyNN.spiNNaker as pynn

    weights_data = _load_b64_npz(_WEIGHTS_NPZ_B64)
    examples_data = _load_b64_npz(_EXAMPLES_NPZ_B64)

    nb_layers = int(weights_data["nb_layers"])
    layers = []
    for i in range(nb_layers):
        layers.append(
            {{
                "W_eff": weights_data[f"layer{{i}}_W_eff"],
                "b_eff": weights_data[f"layer{{i}}_b_eff"],
                "alpha": weights_data[f"layer{{i}}_alpha"],
                "threshold": float(weights_data[f"layer{{i}}_threshold"]),
                "is_readout": bool(weights_data[f"layer{{i}}_is_readout"]),
            }}
        )

    nb_inputs = layers[0]["W_eff"].shape[1]
    nb_outputs = layers[-1]["W_eff"].shape[0]
    n_examples = int(examples_data["n_examples"])

    correct = 0
    for j in range(n_examples):
        times_sec = examples_data[f"example{{j}}_times"]
        units = examples_data[f"example{{j}}_units"]
        label = int(examples_data[f"example{{j}}_label"])

        duration_ms = DT_MS * 100

        pynn.setup(timestep=SIM_TIMESTEP_MS, min_delay=SIM_TIMESTEP_MS)
        input_spike_times = spike_times_to_pynn(times_sec, units, nb_inputs)
        populations, projections, readout_pop = build_network(
            pynn, layers, input_spike_times
        )
        pynn.run(duration_ms)
        pred, spike_counts = spike_count_argmax(readout_pop, nb_outputs)
        pynn.end()

        correct += pred == label
        print(
            f"example {{j}}: label={{label}} pynn_pred={{pred}} "
            f"match={{pred == label}} spike_counts={{spike_counts.tolist()}}"
        )

    print(f"\\nSpiNNaker PyNN accuracy: {{correct}}/{{n_examples}}")


if __name__ == "__main__":
    main()
'''


def main():
    args = parse_args()

    weights_b64 = npz_to_b64(args.weights)
    examples_b64 = build_examples_npz_b64(args.shd_h5, args.n_examples, args.seed)
    model_src = read_model_src()

    script = TEMPLATE.format(
        n_examples=args.n_examples,
        weights_b64=weights_b64,
        examples_b64=examples_b64,
        model_src=model_src,
    )

    with open(args.out, "w") as f:
        f.write(script)

    print(f"Generated {args.out} ({len(script)} bytes)")


if __name__ == "__main__":
    main()
